core/urls.py
from django.urls import path
from core.views import IndexView

urlpatterns = [
    path('', IndexView.as_view(), name='home'),
]

forms/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from api.views import ProductInCartViewSet

router = DefaultRouter()
router.register(r'productincart', ProductInCartViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
    path('', include(("core.urls", "core"), namespace='main')),
    path('auth/', include(("loginsys.urls", "loginsys"), namespace='loginsys')),
    path('food/', include(("foodsys.urls", "foodsys"), namespace='foodsys')),
    path('orders/', include(("ordersys.urls", "ordersys"), namespace='ordersys')),
    # path('api-auth/', include('rest_framework.urls')),
    # path('api/v1/', include(router.urls)),
]

loginsys/urls.py
from django.urls import path
from django.conf.urls import url
from loginsys.views import login, logout, RegistrationView, ProfileView, UserUpdateView, profile_change_password, profile_personal_data

urlpatterns = [
    url('login/', login, name='login'),
    url('logout/', logout, name='logout'),
    url('registration/', RegistrationView.as_view(), name='registration'),
    path('update-user/<str:username>/', UserUpdateView.as_view(), name='update-user'),
    url('profile/', ProfileView.as_view(), name='profile'),
    url('change-password/', profile_change_password, name='profile-change-password'),
    url('personal-data/', profile_personal_data, name='profile-personal-data'),
]

loginsys/models.py
import uuid
from django.core.validators import RegexValidator
from django.db import models
from django.contrib.auth.models import AbstractUser


class MyUser(AbstractUser):
    phone_regex = RegexValidator(
        regex=r'^\+380\d{9}$',
        message="Phone number must be entered in the format: '+380XXXXXXXXX'. 12 digits."
    )

    uuid = models.UUIDField(default=uuid.uuid4, unique=True)
    phone = models.CharField(validators=[phone_regex], max_length=13, blank=True, unique=True)
    address = models.CharField(max_length=255, null=True)
    bonuses = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    USERNAME_FIELD = 'phone'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return str(self.phone)

loginsys/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.core.validators import RegexValidator


class LoginForm(forms.Form):
    phone = forms.CharField(max_length=13, required=True, validators=[RegexValidator(r'^\+380\d{9}$', message="Phone number must be entered in the format: '+380XXXXXXXXX'. 12 digits.")])
    password = forms.CharField(max_length=255, widget=forms.PasswordInput)

    def clean_phone(self):
        phone = self.cleaned_data.get('phone')
        if not get_user_model().objects.filter(phone=phone):
            raise forms.ValidationError('User not found')
        return phone

    def clean_password(self, *args, **kwargs):
        phone = self.cleaned_data.get('phone')
        password = self.cleaned_data.get('password')
        if phone and password:
            user = get_user_model().objects.get(phone=phone)
            if not user.check_password(password):
                raise forms.ValidationError("Incorrect password")
        return super(LoginForm, self).clean(*args, **kwargs)


class OrderingContactForm(forms.Form):
    username = forms.CharField(required=True)
    phone = forms.CharField(max_length=13, required=True, validators=[RegexValidator(r'^\+380\d{9}$', message="Phone number must be entered in the format: '+380XXXXXXXXX'. 12 digits.")])
    address = forms.CharField(required=True)

    class Meta:
        model = get_user_model()
        fields = ('phone', 'username', 'address')

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super(OrderingContactForm, self).__init__(*args, **kwargs)

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if self.user.is_anonymous or self.user.username != username:
            if get_user_model().objects.filter(username=username):
                raise forms.ValidationError(
                    'This username is already in use')
        return username

    def clean_phone(self):
        phone = self.cleaned_data.get('phone')
        if self.user.is_anonymous or self.user.phone != phone:
            if get_user_model().objects.filter(phone=phone):
                raise forms.ValidationError(
                    'This phone is already in use')
        return phone


class PasswordChangeForm(forms.Form):
    old_password = forms.CharField(widget=forms.widgets.PasswordInput())
    password = forms.CharField(widget=forms.widgets.PasswordInput())
    password_confirm = forms.CharField(widget=forms.widgets.PasswordInput())


class RegistrationForm(forms.ModelForm):
    username = forms.CharField(required=True)
    phone = forms.CharField(max_length=13, required=True, initial='+380')
    password_confirm = forms.CharField(widget=forms.widgets.PasswordInput())

    class Meta:
        model = get_user_model()
        fields = ('username', 'phone', 'password', 'password_confirm', )
        widgets = {
            'password': forms.widgets.PasswordInput()
        }

    def clean_password_confirm(self):
        if self.cleaned_data['password_confirm'] != self.cleaned_data['password']:
            raise forms.ValidationError("Passwords do not match")
        return self.cleaned_data['password']

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password'])
        user.save()
        return user


class PersonalDataUpdateForm(forms.ModelForm):
    username = forms.CharField(required=True)
    phone = forms.CharField(max_length=13, required=True)
    address = forms.CharField(required=False)

    class Meta:
        model = get_user_model()
        help_texts = {
            'username': None,
        }
        fields = ('username', 'phone', 'address')

loginsys/views.py
from django.http import HttpResponse, Http404
from django.shortcuts import render
from django.urls.base import reverse_lazy
from django.views.generic import CreateView, UpdateView
from django.contrib.auth import get_user_model
from django.contrib.auth import update_session_auth_hash
from django.views.generic.base import TemplateView
from django.shortcuts import redirect
from django.contrib import auth
from django.template.context_processors import csrf
from ordersys.models import Order, ProductInOrder
from .forms import PasswordChangeForm, PersonalDataUpdateForm, LoginForm, RegistrationForm


def login(request):
    args = {}
    args.update(csrf(request))
    form = LoginForm(request.POST or None)

    if request.POST:
        if form.is_valid():
            phone = request.POST.get('phone', '')
            password = request.POST.get('password', '')
            user = auth.authenticate(username=phone, password=password)
            if user is not None:
                auth.login(request, user)
                return redirect('/')

    args['form'] = form

    return render(request, 'login.html', args)


def logout(request):
    auth.logout(request)
    return redirect("main:home")


class RegistrationView(CreateView):
    model = get_user_model()
    form_class = RegistrationForm
    template_name = 'registration.html'
    success_url = reverse_lazy('main:home')


class UserUpdateView(UpdateView):
    template_name = 'update_user.html'

    def dispatch(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return super(UserUpdateView, self).dispatch(*args, **kwargs)
        else:
            HttpResponse(status_code=404)

    success_url = reverse_lazy('loginsys:profile-personal-data')
    model = get_user_model()
    form_class = PersonalDataUpdateForm
    slug_field = "username"
    slug_url_kwarg = "username"


def profile_change_password(request):
    if not request.user.is_authenticated:
        raise Http404

    args = {}
    args.update(csrf(request))
    form = PasswordChangeForm()
    user = get_user_model().objects.get(username=auth.get_user(request).username)

    if request.method == 'POST':
        password = request.POST.get('password')
        password_confirm = request.POST.get('password_confirm')
        old_password = request.POST.get('old_password')
        if user.check_password(old_password):
            if password == password_confirm:
                user.set_password(password)
                user.save()
                update_session_auth_hash(request, user)
                args['password_error'] = "Ok"
                args['ok'] = 'Ok'
            else:
                args['password_error'] = "Passwords do not match"
        else:
            args['password_error'] = "Incorrect old password"
    return render(request, 'profile_password_change.html', context={'args': args, 'form': form})


class ProfileView(TemplateView):
    template_name = "profile.html"

    def dispatch(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return super(ProfileView, self).dispatch(*args, **kwargs)
        else:
            HttpResponse(status_code=404)

    def get_context_data(self, *args, **kwargs):
        context = super(ProfileView, self).get_context_data(*args, **kwargs)
        context['username'] = auth.get_user(self.request).username
        context['bonuses'] = get_user_model().objects.get(username=auth.get_user(self.request).username).bonuses
        user_orders = Order.objects.filter(user__username=context['username'])
        orders = []
        for user_order in user_orders:
            order = []
            products_in_order = ProductInOrder.objects.filter(order=user_order)
            order.append(user_order)
            order.append(products_in_order)
            orders.append(order)
        if orders:
            context['orders'] = reversed(orders)
        return context


def profile_personal_data(request):
    if not request.user.is_authenticated:
        raise Http404

    user = get_user_model().objects.filter(username=auth.get_user(request).username)
    return render(request, 'profile_personal_data.html', locals())

loginsys/templates/login.html
{% extends 'base.html' %}
{% block login %}
<form class="form login-form" method="post">{% csrf_token %}
        <div class="form-group">
            <label>Phone</label>
            <span class="form-error">{{ form.phone.errors }}</span>
            <input class="form-control" type="text" name="{{ form.phone.html_name }}" value="+380">
        </div>
        <div class="form-group">
            <label>Password</label>
            <span class="form-error">{{ form.password.errors }}</span>
            <input class="form-control" type="password" name="{{ form.password.html_name }}">
        </div>
    <input class="btn btn-success" type="submit" value="Sign In">
    <a class="register-btn" href="{% url 'loginsys:registration' %}" style="color: green;">Registration</a>
</form>
{% endblock %}

loginsys/templates/profile.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    {% include "profile_navbar.html" %}
    <div class="row">
        <div class="col-6">
            <h4 class="text-center profile-head-text">History</h4>
            <div  id="profile_history_block">
            {% if orders %}
                {% for order in orders %}
                <div class="container-fluid history-order">
                    <div class="mg-t5">{{order.0}}</div>
                    <ul class="mg-t10">
                    {% for product in order.1 %}
                        <li>{{product}} {{product.nmb}} шт - {{product.total_price}} ₴</li>
                    {% endfor %}
                    </ul>
                    <div class="text-right">{{order.0.created}}</div>
                    <div class="text-right mg-b5">{{order.0.total_price}} ₴</div>
                </div>
                {% endfor %}
            {% else %}
                <h5 class="text-center no-orders">No Orders</h5>
            {% endif %}
            </div>
        </div>
        <div class="col-6">
            <h4 class="text-center profile-head-text">Bonuses</h4>
            <h1 class="text-center">{{bonuses}}</h1>
        </div>
    </div>
</div>
{% endblock content %}

loginsys/templates/profile_navbar.html
<nav class="navbar navbar-light bg-light profile-nav mg-t20">
  <h5 class="text-center">PROFILE</h5>
  <form class="form-inline">
    <a class="btn btn-outline-success profile-menu" href="{% url 'loginsys:profile' %}" type="button">History</a>
    <a class="btn btn-outline-success profile-menu" href="{% url 'loginsys:profile-personal-data' %}" type="button">Personal Data</a>
    <a class="btn btn-outline-success profile-menu" href="{% url 'loginsys:profile-change-password' %}" type="button">Password Change</a>
  </form>
</nav>

loginsys/templates/profile_password_change.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
{% include "profile_navbar.html" %}
    <div class="row">
        <div class="col-md-4">
            <form id="password-change-form" role="form" method="post">{% csrf_token %}
                {{ form|crispy }}
                <div class="row" id="password-change-button">
                    <button type="submit" class="btn btn-success">Submit</button>
                    {% if args.password_error %}
                        {% if args.password_error == args.ok %}
                            <div style="color: green;" class="password-change-text">{{ args.password_error }}</div>
                        {% else %}
                            <div class="password-change-text">{{ args.password_error }}</div>
                        {% endif %}
                    {% endif %}
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

loginsys/templates/profile_personal_data.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    {% include "profile_navbar.html" %}
    <div class="row">
        <div class="col-md-6">
            <div id="personal_data">
                <h6>Username: {{user.0.username}}</h6>
                <h6>Phone: {{user.0.phone}}</h6>
                <h6>Address: {{user.0.address}}</h6>
            </div>
            <a class="btn btn-success" href="{% url 'loginsys:update-user' user.0.username %}">Edit</a>
        </div>
    </div>
</div>
{% endblock content %}

loginsys/templates/registration.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<form role="form" class="register-form" method="post">{% csrf_token %}
    {{ form|crispy }}
    <div class="form-group">
      <button type="submit" class="btn btn-success">Register</button>
    </div>
</form>
{% endblock content %}

loginsys/templates/update_user.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<form role="form" method="post">{% csrf_token %}
    <div class="col-md-4">
    {{ form|crispy }}
        <div class="form-group">
            <button type="submit" class="btn btn-success">Update</button>
        </div>
    </div>
</form>
{% endblock content %}