core/urls.py
from django.urls import path
from core.views import IndexView

urlpatterns = [
    path('', IndexView.as_view(), name='home'),
]

foodsys/urls.py
from django.conf.urls import url
from foodsys.views import ProductView, Menu01View, Menu02View, Menu03View, Menu04View

urlpatterns = [
    url('product/', ProductView.as_view(), name='product'),
    url('menu01/', Menu01View.as_view(), name='menu01'),
    url('menu02/', Menu02View.as_view(), name='menu02'),
    url('menu03/', Menu03View.as_view(), name='menu03'),
    url('menu04/', Menu04View.as_view(), name='menu04'),
]

forms/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from api.views import ProductInCartViewSet

router = DefaultRouter()
router.register(r'productincart', ProductInCartViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
    path('', include(("core.urls", "core"), namespace='main')),
    path('auth/', include(("loginsys.urls", "loginsys"), namespace='loginsys')),
    path('food/', include(("foodsys.urls", "foodsys"), namespace='foodsys')),
    path('orders/', include(("ordersys.urls", "ordersys"), namespace='ordersys')),
    # path('api-auth/', include('rest_framework.urls')),
    # path('api/v1/', include(router.urls)),
]

loginsys/urls.py
from django.urls import path
from django.conf.urls import url
from loginsys.views import login, logout, RegistrationView, ProfileView, UserUpdateView, profile_change_password, profile_personal_data

urlpatterns = [
    url('login/', login, name='login'),
    url('logout/', logout, name='logout'),
    url('registration/', RegistrationView.as_view(), name='registration'),
    path('update-user/<str:username>/', UserUpdateView.as_view(), name='update-user'),
    url('profile/', ProfileView.as_view(), name='profile'),
    url('change-password/', profile_change_password, name='profile-change-password'),
    url('personal-data/', profile_personal_data, name='profile-personal-data'),
]

ordersys/urls.py
from django.conf.urls import url
from ordersys.views import cart_adding, CartView, checkout, payed_online, card, thank

urlpatterns = [
    url('cart/', CartView.as_view(), name='cart'),
    url('cart_adding/', cart_adding, name='cart_adding'),
    url('checkout/', checkout, name='checkout'),
    url('payed-online-order/', payed_online, name='payed_online'),
    url('card/', card, name='card'),
    url('thank/', thank, name='thank')
]

core/views.py
from django.views.generic.base import TemplateView
from foodsys.models import Product
from ordersys.models import ProductStatistic


class IndexView(TemplateView):
    template_name = "index.html"

    def get_context_data(self, *args, **kwargs):

        main_page_products_nmb = 6
        products = []
        product_statistics = ProductStatistic.objects.all().order_by('nmb_in_orders').reverse()[:main_page_products_nmb]
        for product_statistic in product_statistics:
            products.append(Product.objects.get(name=product_statistic.name))

        if len(product_statistics) < main_page_products_nmb:

            for product in Product.objects.all():
                for stat_prod in products:
                    if stat_prod == product:
                        break
                else:
                    products.append(product)
                    if len(products) == main_page_products_nmb:
                        break

        context = {
            'products': products,
        }

        return context

core/templates/base.html
{% load static %}
<html>
    <head>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        {% block css %}{% endblock css %}
        {% block meta %}{% endblock meta %}
    </head>
    <body>
        <br>
        <div class="container base-container">

            <form id="csrf_getting_form">{% csrf_token %}</form>

            {% include "navbar.html" %}
            {% block content %}{% endblock content %}
            {% block login %}{% endblock login %}
        </div>
        <script
			  src="https://code.jquery.com/jquery-3.5.1.js"
			  integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
			  crossorigin="anonymous">
        </script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
        <script src="https://js.stripe.com/v3/"></script>
        <script src="{% static 'js/scripts.js' %}"></script>
        {% block js %}{% endblock js %}
    </body>
</html>

core/templates/form.html
{% load crispy_forms_tags %}
<form role="form" method="post">{% csrf_token %}
    {{ form|crispy }}
    <div class="form-group">
      <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>

core/templates/index.html
{% extends "base.html" %}
{% block content %}
    <div class="container products-container">
        <div class="row mg-b5">
            {% for product in products %}
            <div class="col-md-4 content mg-t30">
                <div class="col-md-12 product-grid" data-id="{{product.id}}">
                    <img src="{{ product.main_image.url }}" class="img-fluid img_prod" alt="Responsive image">
                    <div class="prod-sh-desc-block">
                        <div>{{ product.short_desc }}</div>
                        <div>{{ product.price }} ₴</div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

core/templates/navbar.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark main-nav">
    <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
        <ul class="navbar-nav mr-auto">

            <li class="nav-item">
              <a class="nav-link" href="{% url 'foodsys:menu01' %}">Burgers</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'foodsys:menu02' %}">Salads & Brkfsts</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'foodsys:menu03' %}">Soups</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'foodsys:menu04' %}">Desserts</a>
            </li>
        </ul>
    </div>
    <div class="mx-auto order-0">
        <a class="navbar-brand mx-auto" href="{% url 'main:home' %}">HOME</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".dual-collapse2">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
    <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
        <ul class="navbar-nav ml-auto">
            {% if username %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'loginsys:profile' %}">Profile</a>
            </li>
            {% endif %}
            <li class="nav-item">
                {% if username %}
                    <a class="nav-link" href="{% url 'loginsys:logout' %}">Logout ({{ username }})</a>
                {% else %}
                    <a class="nav-link" href="{% url 'loginsys:login' %}">Sign In</a>
                {% endif %}
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'ordersys:cart' %}">Cart<span id="cart_total_amount"></span><span id="cart_total_nmb">
                    {% if products_total_nmb %}
                        ({{ products_total_nmb }})
                    {% else %}
                        (0)
                    {% endif %}
                </span></a>
            </li>
        </ul>
    </div>
</nav>