core/urls.py
from django.urls import path
from core.views import IndexView

urlpatterns = [
    path('', IndexView.as_view(), name='home'),
]

forms/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from api.views import ProductInCartViewSet

router = DefaultRouter()
router.register(r'productincart', ProductInCartViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
    path('', include(("core.urls", "core"), namespace='main')),
    path('auth/', include(("loginsys.urls", "loginsys"), namespace='loginsys')),
    path('food/', include(("foodsys.urls", "foodsys"), namespace='foodsys')),
    path('orders/', include(("ordersys.urls", "ordersys"), namespace='ordersys')),
    # path('api-auth/', include('rest_framework.urls')),
    # path('api/v1/', include(router.urls)),
]

ordersys/urls.py
from django.conf.urls import url
from ordersys.views import cart_adding, CartView, checkout, payed_online, card, thank

urlpatterns = [
    url('cart/', CartView.as_view(), name='cart'),
    url('cart_adding/', cart_adding, name='cart_adding'),
    url('checkout/', checkout, name='checkout'),
    url('payed-online-order/', payed_online, name='payed_online'),
    url('card/', card, name='card'),
    url('thank/', thank, name='thank')
]

ordersys/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.db.models.signals import post_save


class ProductStatistic(models.Model):
    name = models.CharField(max_length=64, blank=True, null=True, default=None)
    nmb_in_orders = models.IntegerField(default=0)

    def __str__(self):
        return self.name


class Order(models.Model):
    METHOD_CARD = 1
    METHOD_CASH = 2
    METHOD_BONUSES = 3

    METHOD_CHOICES = (
        (METHOD_CARD, 'Payment by Card'),
        (METHOD_CASH, 'Payment by Cash'),
        (METHOD_BONUSES, 'Payment by Bonuses')
    )

    STATUS_NEW = 1
    STATUS_IN_WORK = 2
    STATUS_CANCELED = 3
    STATUS_CLOSED = 4
    STATUS_PAYED = 5

    STATUS_CHOICES = (
        (STATUS_NEW, 'New'),
        (STATUS_IN_WORK, 'In work'),
        (STATUS_CANCELED, 'Canceled'),
        (STATUS_CLOSED, 'Closed'),
        (STATUS_PAYED, 'Payed')
    )

    user = models.ForeignKey(get_user_model(), blank=True, null=True, default=None, on_delete=models.SET_NULL)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0)  # total price for all products in order
    customer_name = models.CharField(max_length=64, blank=True, null=True, default=None)
    customer_email = models.EmailField(blank=True, null=True, default=None)
    customer_address = models.CharField(max_length=255, blank=True, null=True)
    customer_phone = models.CharField(max_length=13, blank=True, null=True)
    comment = models.TextField(blank=True, null=True, default=None)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    status = models.PositiveSmallIntegerField(choices=STATUS_CHOICES)
    payment_method = models.PositiveSmallIntegerField(choices=METHOD_CHOICES)

    def __str__(self):
        return "Заказ %s %s" % (self.id, self.status)

    class Meta:
        verbose_name = 'Order'
        verbose_name_plural = 'Orders'

    def save(self, *args, **kwargs):

        super(Order, self).save(*args, **kwargs)


class ProductInOrder(models.Model):
    order = models.ForeignKey(Order, blank=True, null=True, default=None, on_delete=models.CASCADE)
    product = models.ForeignKey("foodsys.Product", blank=True, null=True, default=None, on_delete=models.CASCADE)
    nmb = models.IntegerField(default=1)
    price_per_item = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0)  # price*nmb
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "%s" % self.product.name

    class Meta:
        verbose_name = 'Product in Order'
        verbose_name_plural = 'Products in Order'

    def save(self, *args, **kwargs):
        price_per_item = self.product.price
        self.price_per_item = price_per_item
        self.total_price = int(self.nmb) * price_per_item
        created = self.pk is None
        super(ProductInOrder, self).save(*args, **kwargs)
        if created:
            product_statistic, created = ProductStatistic.objects.get_or_create(name=self.product.name, defaults={"name": self.product.name})
            product_statistic.nmb_in_orders += int(self.nmb)
            product_statistic.save(force_update=True)


class ProductInCart(models.Model):
    user_id = models.IntegerField(blank=True, null=True)
    session_key = models.CharField(max_length=128, blank=True, null=True, default=None)
    order = models.ForeignKey(Order, blank=True, null=True, default=None, on_delete=models.CASCADE)
    product = models.ForeignKey("foodsys.Product", blank=True, null=True, default=None, on_delete=models.CASCADE)
    nmb = models.IntegerField(default=1)
    price_per_item = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "%s" % self.product.name

    class Meta:
        verbose_name = "Product in Cart"
        verbose_name_plural = "Products in Cart"

    def save(self, *args, **kwargs):
        price_per_item = self.product.price
        self.price_per_item = price_per_item
        self.total_price = int(self.nmb) * price_per_item

        super(ProductInCart, self).save(*args, **kwargs)


def product_in_order_post_save(sender, instance, created, **kwargs):
    order = instance.order
    all_products_in_order = ProductInOrder.objects.filter(order=order, is_active=True)
    order_total_price = 0

    for item in all_products_in_order:
        order_total_price += item.total_price

    instance.order.total_price = order_total_price
    instance.order.save(force_update=True)


post_save.connect(product_in_order_post_save, sender=ProductInOrder)

ordersys/views.py
import stripe
from decimal import Decimal
from django.conf import settings
from django.shortcuts import render
from django.contrib.auth import get_user_model
from django.views.generic.base import TemplateView
from django.shortcuts import redirect
from django.http import JsonResponse, Http404
from .models import ProductInOrder, ProductInCart, Order
from loginsys.forms import OrderingContactForm
from foodsys.models import Product


def checkout(request):
    if request.user.is_authenticated:
        products_in_cart = ProductInCart.objects.filter(user_id=get_user_model().objects.get(
            username=request.user.username).id, is_active=True, order__isnull=True)
    else:
        products_in_cart = ProductInCart.objects.filter(session_key=request.session.session_key, is_active=True, order__isnull=True)
    if not products_in_cart:
        raise Http404

    radio_cash = "cashRadio"
    radio_bonuses = "bonusesRadio"
    radio_card = "cardRadio"

    args = {}
    final_price = 0
    user = request.user
    form = OrderingContactForm(request.POST or None, user=request.user)

    for product in products_in_cart:
        final_price += product.total_price

    # CASH LOGIC
    def logic_cash():
        order = Order.objects.create(user=customer, customer_name=data["username"],
                                     customer_phone=data["phone"],
                                     customer_address=data["address"], status=Order.STATUS_IN_WORK,
                                     payment_method=Order.METHOD_CASH,
                                     comment=data["comment"])

        for name, value in data.items():
            if name.startswith("product_in_cart_"):
                product_in_cart_id = name.split("product_in_cart_")[1]
                product_in_cart = ProductInCart.objects.get(id=product_in_cart_id)
                product_in_cart.nmb = value
                product_in_cart.order = order
                product_in_cart.save(force_update=True)
                ProductInOrder.objects.create(product=product_in_cart.product, nmb=product_in_cart.nmb,
                                              price_per_item=product_in_cart.price_per_item,
                                              total_price=product_in_cart.total_price,
                                              order=order)

        if request.user.is_authenticated:
            ProductInCart.objects.filter(user_id=customer.id).delete()
        else:
            ProductInCart.objects.filter(session_key=request.session.session_key).delete()

        def delete_customer():
            if not request.user.is_authenticated:
                customer.delete()
        delete_customer()

    # BONUSES LOGIC
    def logic_bonuses():
        if customer.bonuses < final_price:
            return "not enough bonuses"
        else:
            customer.bonuses -= final_price
            customer.save(force_update=True)

        order = Order.objects.create(user=customer, customer_name=data["username"],
                                     customer_phone=data["phone"],
                                     customer_address=data["address"], status=Order.STATUS_PAYED,
                                     payment_method=Order.METHOD_BONUSES,
                                     comment=data["comment"])

        for name, value in data.items():
            if name.startswith("product_in_cart_"):
                product_in_cart_id = name.split("product_in_cart_")[1]
                product_in_cart = ProductInCart.objects.get(id=product_in_cart_id)
                product_in_cart.nmb = value
                product_in_cart.order = order
                product_in_cart.save(force_update=True)
                ProductInOrder.objects.create(product=product_in_cart.product, nmb=product_in_cart.nmb,
                                              price_per_item=product_in_cart.price_per_item,
                                              total_price=product_in_cart.total_price,
                                              order=order)

        if request.user.is_authenticated:
            ProductInCart.objects.filter(user_id=customer.id).delete()
        else:
            ProductInCart.objects.filter(session_key=request.session.session_key).delete()

        def delete_customer():
            if not request.user.is_authenticated:
                customer.delete()
        delete_customer()

    # CARD LOGIC
    def logic_card():
        order = Order.objects.create(user=customer, customer_name=data["username"],
                                     customer_phone=data["phone"],
                                     customer_address=data["address"], status=Order.STATUS_NEW,
                                     payment_method=Order.METHOD_CARD,
                                     comment=data["comment"])

        for name, value in data.items():
            if name.startswith("product_in_cart_"):
                product_in_cart_id = name.split("product_in_cart_")[1]
                product_in_cart = ProductInCart.objects.get(id=product_in_cart_id)
                product_in_cart.nmb = value
                product_in_cart.order = order
                product_in_cart.save(force_update=True)
                ProductInOrder.objects.create(product=product_in_cart.product, nmb=product_in_cart.nmb,
                                              price_per_item=product_in_cart.price_per_item,
                                              total_price=product_in_cart.total_price,
                                              order=order)

        if request.user.is_authenticated:
            ProductInCart.objects.filter(user_id=customer.id).delete()
        else:
            ProductInCart.objects.filter(session_key=request.session.session_key).delete()

        def delete_customer():
            if not request.user.is_authenticated:
                customer.delete()

        request.session['customer_username'] = customer.username
        request.session['order_id'] = order.id
        request.session['customer_id'] = customer.id
        delete_customer()

    args['final_price'] = final_price
    args['user'] = user
    args['form'] = form

    if request.POST:
        if form.is_valid():

            customer = request.user
            data = request.POST

            if request.user.is_authenticated:
                get_user_model().objects.filter(username=request.user.username).update(
                    username=data["username"],
                    phone=data["phone"],
                    address=data["address"])
                customer = get_user_model().objects.get(username=data["username"])
            else:
                customer = get_user_model().objects.create(
                    username=data["username"],
                    phone=data["phone"],
                    address=data["address"])

            if request.POST['customRadio'] == radio_bonuses:
                if logic_bonuses() == "not enough bonuses":
                    args['no_bonuses'] = True
                    return render(request, 'checkout.html', args)
                else:
                    return redirect('ordersys:thank')
            elif request.POST['customRadio'] == radio_cash:
                logic_cash()
                return redirect('ordersys:thank')
            elif request.POST['customRadio'] == radio_card:
                logic_card()
                return redirect('ordersys:card')

    return render(request, 'checkout.html', args)


def card(request):
    if not request.session.get('order_id'):
        raise Http404

    stripe.api_key = settings.STRIPE_PRIVATE_KEY
    # 65000.00

    intent = stripe.PaymentIntent.create(
        amount=int(Order.objects.get(id=request.session['order_id']).total_price * 100),
        currency='uah',
        # Verify your integration in this guide by including this parameter
        metadata={'integration_check': 'accept_a_payment'},)

    client_secret = intent.client_secret

    return render(request, 'card.html', {'client_secret': client_secret, 'intent': intent})


def payed_online(request):
    if request.POST:
        order = Order.objects.get(id=request.session['order_id'])
        order.status = Order.STATUS_PAYED
        order.save()
        if request.user.is_authenticated:
            customer = get_user_model().objects.get(id=request.session['customer_id'])
            customer.bonuses += order.total_price * Decimal("0.01")
            customer.save()

        del request.session['customer_username']
        del request.session['order_id']
        del request.session['customer_id']

        return JsonResponse({"status": "payed"})


class CartView(TemplateView):
    template_name = "cart.html"

    def get_context_data(self, *args, **kwargs):
        context = super(CartView, self).get_context_data(*args, **kwargs)

        return context


def cart_adding(request):
    return_dict = dict()
    session_key = request.session.session_key
    data = request.POST
    product_id = data.get("product_id")
    nmb = data.get("nmb")
    is_delete = data.get("is_delete")

    if is_delete == "true":
        if request.user.is_authenticated:
            ProductInCart.objects.filter(user_id=get_user_model().objects.get(username=request.user.username).id,
                                         is_active=True,
                                         order__isnull=True,
                                         product__id=product_id
                                         ).update(is_active=False)
        else:
            ProductInCart.objects.filter(session_key=session_key,
                                         is_active=True,
                                         order__isnull=True,
                                         product__id=product_id
                                         ).update(is_active=False)

    else:

        def not_created_product_in_cart(count):
            new_product.nmb += int(count)

ordersys/templates/card.html
{% extends "base.html" %}
{% load static %}
{% block js %}<script src="{% static 'js/payment.js' %}"></script>{% endblock js %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3 class="text-center mg-t30">Pay order by card</h3>
                <form id="payment-form" class="card-form" name="order">
                    <div id="card-element" class="mt-5 mb-5">
                    </div>
                    <div id="card-errors" class="mg-b15" role="alert"></div>
                    <button type="submit" data-username="{{ request.session.customer_username }}" class="btn btn-success btn-block" id="card-btn" data-secret="{{ client_secret }}">Pay</button>
                </form>
        </div>
    </div>
</div>
{% endblock content %}

ordersys/templates/cart.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container">
    <div class="row">
        {% if products_in_cart %}
            <div class="col-md-12">
                <h3 class="text-center mg-t20 mg-b20">Products in cart</h3>
                <form class="form-horizontal" method="post">{% csrf_token %}
                    <table class="table">
                        <tr>
                            <th>Product</th>
                            <th></th>
                            <th>Number</th>
                            <th>Price per item</th>
                            <th>Price</th>
                            <th></th>
                        </tr>
                        {% for product_in_cart in products_in_cart %}
                        <tr>
                            <td>
                               {{ product_in_cart.product.name }}
                            </td>
                            <td>
                                <img src="{{ product_in_cart.product.main_image.url }}" class="img-cart">
                            </td>
                            <td>
                               <span>{{ product_in_cart.nmb }}</span>
                            </td>
                            <td>
                                <span class="product-price">
                                    {{ product_in_cart.price_per_item }} ₴
                                </span>
                            </td>
                            <td>
                                <span class="total-product-in-cart-amount">
                                    {{ product_in_cart.total_price }} ₴
                                </span>
                            </td>
                            <td>
                                <a class="delete-item" href="#" data-product_id="{{product_in_cart.product.id}}" data-product_total_price="{{product_in_cart.total_price}}">X</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </table>
                    <div class="text-right">
                        <b>Total price: </b> <span id="total_order_amount"></span> ₴
                    </div>
                    <br>
                    <div class="text-right">
                        <a class="btn btn-success" id="checkout_btn" href="{% url 'ordersys:checkout' %}">Checkout</a>
                    </div>
                </form>
            </div>
        {% else %}
        <div class="col-md-12 empty-cart">
            <h4 class="text-center no-items-in-cart-text">There are no items in your cart</h4>
        </div>
        {% endif %}
    </div>
</div>
{% endblock content %}

ordersys/templates/checkout.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <form class="form-horizontal" method="post">{% csrf_token %}
                <div class="form-group">
                    <label>Name*</label>
                    <span class="form-error">{{ form.username.errors }}</span>
                    <input type="text" name="{{ form.username.html_name }}" class="form-control" value="{{user.username}}">
                </div>
                <div class="form-group">
                    <label>Phone*</label>
                    <span class="form-error">{{ form.phone.errors }}</span>
                    <input type="text" name="{{ form.phone.html_name }}" class="form-control" {% if user.phone %}value="{{user.phone}}"{% else %}value="+380"{% endif %}>
                </div>
                <div class="form-group">
                    <label>Address*</label>
                    <span class="form-error">{{ form.address.errors }}</span>
                    <input type="text" name="{{ form.address.html_name }}" class="form-control" {% if user.address %}value="{{user.address}}"{% endif %}>
                </div>
                <div class="form-group">
                    <label>Comment</label>
                    <textarea name="comment" class="form-control" value="{{ request.POST.comment }}"></textarea>
                </div>
                <div class="custom-control custom-radio">
                  <input type="radio" id="cashRadio" name="customRadio" class="custom-control-input" checked="checked" value="cashRadio">
                  <label class="custom-control-label" for="cashRadio">Pay order by Cash</label>
                </div>
                <div class="custom-control custom-radio">
                  <input type="radio" id="bonusesRadio" name="customRadio" class="custom-control-input" value="bonusesRadio"
                     {% if not user.is_authenticated %}
                        disabled
                     {% endif %}>
                  <label class="custom-control-label" for="bonusesRadio">Pay order by Bonuses</label>
                </div>
                <div class="custom-control custom-radio">
                  <input type="radio" id="cardRadio" name="customRadio" class="custom-control-input" value="cardRadio">
                  <label class="custom-control-label" for="cardRadio">Pay order by Card</label>
                </div>

                {% for product_in_cart in products_in_cart %}
                       <input hidden="true" value="{{ product_in_cart.nmb }}" type="number"
                              class="product-in-cart-nmb" name="product_in_cart_{{ product_in_cart.id }}">
                {% endfor %}

                <button class="btn btn-success" id="pay_btn">Confirm</button>
            </form>

        </div>
        <div class="col-md-6">
            <div class="row">
                <div class="col-md-6">
                    {% if user.is_authenticated %}
                    <h4 class="text-center bonuses">Bonuses: {{ user.bonuses }} ₴</h4>
                    {% endif %}
                    {% if no_bonuses %}
                        <h5 class="text-center" style="color: red;">Not enough bonuses</h5>
                    {% endif %}
                </div>
                <div class="col-md-6">
                    <h4 class="text-center final-price">Price: {{ final_price }} ₴</h4>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

ordersys/templates/thank.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container">
    <div class="row mg-b5">
        <div class="col-md-12">
            <h3 class="text-center mg-t20">Thank You</h3>
        </div>
        <div class="container products-container">
            <div class="row mg-t10">
                {% for product in products|slice:":3" %}
                <div class="col-md-4 content">
                    <div class="col-md-12 ad-grid">
                        <img src="{{ product.main_image.url }}" class="img-fluid img_prod" alt="Responsive image">
                        <div class="prod-sh-desc-block">{{ product.short_desc }}</div>
                        <div>{{ product.price }} ₴</div>
                    </div>
                </div>
                {% endfor %}
            </div>
            <div class="row justify-content-center mg-t30">
                {% for product in products|slice:"3:" %}
                <div class="col-md-4 content">
                    <div class="col-md-12 ad-grid">
                        <img src="{{ product.main_image.url }}" class="img-fluid img_prod" alt="Responsive image">
                        <div class="prod-sh-desc-block">
                            <div>{{ product.short_desc }}</div>
                            <div>{{ product.price }} ₴</div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock content %}